### ISSUE TITLE
Credit to SqlBulkTools

### ISSUE THREAD

**Issue by gtaylor44** [tiagoln/EntityFramework.BulkExtensions#1]
Hello, I'm the author of SqlBulkTools. I noticed that you have copied and pasted a lot of code to make this library without forking or giving credit. Please consider giving credit to SqlBulkTools.

**Comment by tiagoln** [comment]
I surely will! I thought of forking it but I realized that I wouldn't need all the code because the purpose was to use the DBContext, so I created a new project from scratch and used mainly the sql manipulation portion of you library code. I just published the library so early because I needed to install it through nuget on a project at work, so I only began to write the documentation this week.

**Comment by tiagoln** [comment]
Just added a credits section, please check it out.

**Comment by gtaylor44** [comment]
Thank you!
